<div style="width:100% !important;border-radius:3px;max-width:600px !important;margin:0 auto;color:#171717;;font-family:Arial,sans-serif;font-size:14px;line-height:1.429;background-color:  #f3f6f7;box-shadow: 0px 1px 2px 1px #d6dde1;">
    <table cellpadding="0" cellspacing="0" width="100%"
           style="border-collapse:collapse;background-color:#f5f5f5;border-collapse:collapse">
        <thead style="background-color: #fff;border-bottom: 1px solid #d6dde1;text-align: left;">
        </thead>
        <tbody>
            <tr>
                <td style="padding:0px;border-collapse:collapse;padding:0 20px">
                    <table cellspacing="0" cellpadding="0" border="0" width="100%" style="border-collapse:collapse;border-spacing:0;border-collapse:separate">
                        <tbody>
                        <tr>
                            <td style="border-radius:0 0 3px 3px;padding:16px 20px;border-collapse:collapse;color:#8899aa;font-size:12px;line-height:18px;font-family:Arial,sans-serif;text-align:center;">
                              <img src="https://umeeshare.com/img/U%20Me%20Share%20Logoxxxhdpi.png" alt="UMee Logo">
                            </td>
                        </tr>
                        </tbody>
                    </table>
                </td>
            </tr>
            <tr>
                <td style="padding:0px;border-collapse:collapse;padding:0 20px">
                    <table cellspacing="0" cellpadding="0" border="0" width="100%"
                           style="border-collapse:collapse;border-spacing:0;border-collapse:separate">
                        <tbody>
                        <tr>
                            <td style="border-collapse:collapse;border:1px solid #d6dde1;padding: 16px 30px;background-color:#fff;">
                                <table cellspacing="0" cellpadding="0" border="0" width="100%" style="border-collapse:collapse;font-family:Arial,sans-serif;font-size:14px;line-height:20px">
                                    <tbody>
                                    <tr>
                                        <td style="padding:0px;border-collapse:collapse;">
                                            <p style="margin:0 0 20px 0;">
                                                Hi <strong style="color: #4dbd74;"><?php echo $name ?></strong>,<br /><br />
                                                
                                                Your account is <strong style="color: #ff0000;">Disabled.</strong><br>
                                                if you want to activate, please contact admin.<br><br>
                                                Best Regards,<br>
                                                <strong style="color: #4dbd74;">Administrator</strong></p>
                                            <div style="margin:10px 0 20px;display:block !important;">
                                                <table cellspacing="0" cellpadding="0" border="0" style="border-collapse:collapse;color:#333;margin:0;">
                                                    <tbody>
                                                    
                                                    </tbody>
                                                </table>
                                            </div>
                                        </td>
                                    </tr>
                                    </tbody>
                                </table>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                </td>
            </tr>
            <tr>
                <td style="padding:0px;border-collapse:collapse;padding:0 20px">
                    <table cellspacing="0" cellpadding="0" border="0" style="border-collapse:collapse;width:100%">
                        <tbody>
                        <tr>
                            <td style="border-radius:0 0 3px 3px;padding:16px 20px;border-collapse:collapse;color:#8899aa;font-size:12px;line-height:18px;font-family:Arial,sans-serif">
                                You are receiving this email because you has been registered as a UMee Share user. If you have any question about this product, please visit our <a href="https://genietree.biz/" target="_blank" style="color: #4dbd74;text-decoration: none; font-weight: bold;">website</a> or drop us an <a href="mailto:info@genietree.biz" style="color: #4dbd74;text-decoration: none; font-weight: bold;">email</a>.
                            </td>
                        </tr>
                        </tbody>
                    </table>
                </td>
            </tr>
        </tbody>
    </table>
</div>