<div style="width:100% !important;border-radius:3px;max-width:600px !important;margin:0 auto;color:#171717;;font-family:Arial,sans-serif;font-size:14px;line-height:1.429;background-color:  #f3f6f7;box-shadow: 0px 1px 2px 1px #d6dde1;">
    <table cellpadding="0" cellspacing="0" width="100%"
           style="border-collapse:collapse;background-color:#f5f5f5;border-collapse:collapse">
        <tbody style="background-color: #fff;border-bottom: 1px solid #d6dde1;text-align: left;">
            <tr>
                <td style="padding:0px;border-collapse:collapse;padding:0 20px">
                    <table cellspacing="0" cellpadding="0" border="0" width="100%" style="border-collapse:collapse;border-spacing:0;border-collapse:separate">
                        <tbody>
                        <tr>
                            <td style="border-radius:0 0 3px 3px;padding:16px 20px;border-collapse:collapse;color:#8899aa;font-size:12px;line-height:18px;font-family:Arial,sans-serif;text-align:center;">
                              <img src="https://umeeshare.com/img/U%20Me%20Share%20Logoxxxhdpi.png" alt="UMee Logo">
                            </td>
                        </tr>
                        </tbody>
                    </table>
                </td>
            </tr>
            <tr>
                <td style="padding:0px;border-collapse:collapse;padding:0 20px">
                    <table cellspacing="0" cellpadding="0" border="0" width="100%"
                           style="border-collapse:collapse;border-spacing:0;border-collapse:separate">
                        <tbody>
                        <tr>
                            <td style="border-collapse:collapse;border:1px solid #d6dde1;padding: 16px 30px;background-color:#fff;">
                                <table cellspacing="0" cellpadding="0" border="0" width="100%" style="border-collapse:collapse;font-family:Arial,sans-serif;font-size:14px;line-height:20px">
                                    <tbody>
                                    <tr>
                                        <td style="padding:0px;border-collapse:collapse;">
                                            <p style="margin:0 0 20px 0;">
                                            Your Billing <strong style="color: #4dbd74;">Paid</strong> Successfully!<br /><br />
                                            We have received payment for your monthly billing.<br /><br />
                                            <p style="margin:0 0 20px 0;">----------------------------------------------------------------------------------------------------------<br /></p>
                                            </p>
                                            <p style="margin:0 0 20px 0;">
                                            	GenieResi RECIEPT - MONTHLY BILLING
                                            </p>
                                            <ul style="list-style: none; padding: 0px;">
                                            	<li>Reference Number : <?php echo $refNum ?></li>
                                            	<li>Period : <?php echo $period ?></li>
                                            	<li>Billing Cycle : <?php echo $cycle ?></li>
                                            	<li>Amount : <?php echo $amount ?></li>
                                            	<li>Payment Method : <?php echo $paymentMethod ?></li>
                                            	<li>Description :<?php echo $statusDesc ?> </li>
                                            </ul>
                                            <br /><br />
                                            <p style="margin:0 0 20px 0;">
                                            	GenieResi, Inc.<br />
                                            	00 2A Cassia Raya Street<br />
                                            	Medan, Indonesia 20132<br />
                                            </p>
                                            <p style="margin:0 0 20px 0;">----------------------------------------------------------------------------------------------------------<br /></p>
                                            <p style="margin:0 0 20px 0;">
                                            	Any question? Please contact <a href="#"><?php echo $contactUs ?></a>
                                            </p>
                                        </td>
                                    </tr>
                                    </tbody>
                                </table>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                </td>
            </tr>
        </tbody>
    </table>
</div>